// List of job roles
export const jobRoles = [
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "UX Designer",
  "Product Manager",
  "DevOps Engineer",
  "Data Scientist",
  "QA Engineer",
  "Marketing Specialist",
  "Sales Representative",
]

// List of possible statuses
const statuses = ["Applied", "Screening", "Interview", "Offer", "Rejected"]

// List of locations
const locations = [
  "New York, NY",
  "San Francisco, CA",
  "Austin, TX",
  "Seattle, WA",
  "Chicago, IL",
  "Boston, MA",
  "Los Angeles, CA",
  "Denver, CO",
  "Atlanta, GA",
  "Remote",
]

// Add a list of skills for different job roles
const skillsByRole = {
  "Frontend Developer": ["React", "JavaScript", "TypeScript", "HTML", "CSS", "Next.js", "Vue", "Angular"],
  "Backend Developer": ["Node.js", "Python", "Java", "C#", "Express", "Django", "Spring Boot", "SQL"],
  "Full Stack Developer": ["React", "Node.js", "JavaScript", "TypeScript", "MongoDB", "Express", "SQL", "Git"],
  "UX Designer": ["Figma", "Sketch", "Adobe XD", "User Research", "Wireframing", "Prototyping", "UI Design"],
  "Product Manager": ["Agile", "Scrum", "Jira", "Product Strategy", "User Stories", "Roadmapping", "Analytics"],
  "DevOps Engineer": ["Docker", "Kubernetes", "AWS", "CI/CD", "Jenkins", "Terraform", "Linux", "Monitoring"],
  "Data Scientist": ["Python", "R", "SQL", "Machine Learning", "TensorFlow", "PyTorch", "Data Visualization"],
  "QA Engineer": ["Selenium", "Jest", "Cypress", "Manual Testing", "Test Planning", "JIRA", "API Testing"],
  "Marketing Specialist": ["SEO", "Content Marketing", "Social Media", "Analytics", "Email Marketing", "CRM"],
  "Sales Representative": ["CRM", "Negotiation", "Prospecting", "Sales Strategy", "Client Relations", "Presentations"],
}

// Generate random date within the last 3 months
function randomDate() {
  const now = new Date()
  const threeMonthsAgo = new Date(now.getFullYear(), now.getMonth() - 3, now.getDate())
  return new Date(threeMonthsAgo.getTime() + Math.random() * (now.getTime() - threeMonthsAgo.getTime())).toISOString()
}

// Generate a random candidate
function generateCandidate(id) {
  const firstNames = [
    "James",
    "Mary",
    "John",
    "Patricia",
    "Robert",
    "Jennifer",
    "Michael",
    "Linda",
    "William",
    "Elizabeth",
    "David",
    "Susan",
    "Richard",
    "Jessica",
    "Joseph",
    "Sarah",
    "Thomas",
    "Karen",
    "Charles",
    "Nancy",
    "Christopher",
    "Lisa",
    "Daniel",
    "Margaret",
    "Matthew",
    "Betty",
    "Anthony",
    "Sandra",
    "Mark",
    "Ashley",
    "Donald",
    "Dorothy",
    "Steven",
    "Kimberly",
    "Paul",
    "Emily",
    "Andrew",
    "Donna",
    "Joshua",
    "Michelle",
    "Kenneth",
    "Carol",
    "Kevin",
    "Amanda",
    "Brian",
    "Melissa",
    "George",
    "Deborah",
    "Timothy",
    "Stephanie",
    "Ronald",
    "Rebecca",
    "Edward",
    "Laura",
    "Jason",
    "Sharon",
    "Jeffrey",
    "Cynthia",
    "Ryan",
    "Kathleen",
    "Jacob",
    "Amy",
    "Gary",
    "Shirley",
    "Nicholas",
    "Angela",
    "Eric",
    "Helen",
    "Jonathan",
    "Anna",
    "Stephen",
    "Brenda",
    "Larry",
    "Pamela",
    "Justin",
    "Nicole",
    "Scott",
    "Samantha",
    "Brandon",
    "Katherine",
    "Benjamin",
    "Emma",
    "Samuel",
    "Ruth",
    "Gregory",
    "Christine",
    "Alexander",
    "Catherine",
    "Frank",
    "Debra",
    "Patrick",
    "Rachel",
    "Raymond",
    "Carolyn",
    "Jack",
    "Janet",
    "Dennis",
    "Virginia",
    "Jerry",
    "Maria",
    "Tyler",
    "Heather",
    "Aaron",
    "Diane",
    "Jose",
    "Julie",
    "Adam",
    "Joyce",
    "Nathan",
    "Victoria",
    "Henry",
    "Kelly",
    "Zachary",
    "Christina",
    "Douglas",
    "Lauren",
    "Peter",
    "Joan",
    "Kyle",
    "Evelyn",
    "Noah",
    "Olivia",
    "Ethan",
    "Judith",
    "Jeremy",
    "Megan",
    "Walter",
    "Cheryl",
    "Christian",
    "Martha",
    "Keith",
    "Andrea",
    "Roger",
    "Frances",
    "Terry",
    "Hannah",
    "Austin",
    "Jacqueline",
    "Sean",
    "Ann",
    "Gerald",
    "Jean",
    "Carl",
    "Alice",
    "Harold",
    "Kathryn",
    "Dylan",
    "Gloria",
    "Arthur",
    "Teresa",
    "Lawrence",
    "Sara",
    "Jordan",
    "Janice",
    "Jesse",
    "Doris",
    "Bryan",
    "Madison",
    "Billy",
    "Julia",
    "Bruce",
    "Grace",
    "Gabriel",
    "Judy",
    "Joe",
    "Abigail",
    "Logan",
    "Marie",
    "Alan",
    "Denise",
    "Juan",
    "Beverly",
    "Albert",
    "Amber",
    "Willie",
    "Theresa",
    "Elijah",
    "Marilyn",
    "Wayne",
    "Danielle",
    "Randy",
    "Diana",
    "Vincent",
    "Brittany",
    "Mason",
    "Natalie",
    "Roy",
    "Sophia",
    "Ralph",
    "Rose",
    "Bobby",
    "Isabella",
    "Russell",
    "Alexis",
    "Bradley",
    "Kayla",
    "Philip",
    "Charlotte",
  ]
  const lastNames = [
    "Smith",
    "Johnson",
    "Williams",
    "Jones",
    "Brown",
    "Davis",
    "Miller",
    "Wilson",
    "Moore",
    "Taylor",
    "Anderson",
    "Thomas",
    "Jackson",
    "White",
    "Harris",
    "Martin",
    "Thompson",
    "Garcia",
    "Martinez",
    "Robinson",
    "Clark",
    "Rodriguez",
    "Lewis",
    "Lee",
    "Walker",
    "Hall",
    "Allen",
    "Young",
    "Hernandez",
    "King",
    "Wright",
    "Lopez",
    "Hill",
    "Scott",
    "Green",
    "Adams",
    "Baker",
    "Gonzalez",
    "Nelson",
    "Carter",
    "Mitchell",
    "Perez",
    "Roberts",
    "Turner",
    "Phillips",
    "Campbell",
    "Parker",
    "Evans",
    "Edwards",
    "Collins",
    "Stewart",
    "Sanchez",
    "Morris",
    "Rogers",
    "Reed",
    "Cook",
    "Morgan",
    "Bell",
    "Murphy",
    "Bailey",
    "Rivera",
    "Cooper",
    "Richardson",
    "Cox",
    "Howard",
    "Ward",
    "Torres",
    "Peterson",
    "Gray",
    "Ramirez",
    "James",
    "Watson",
    "Brooks",
    "Kelly",
    "Sanders",
    "Price",
    "Bennett",
    "Wood",
    "Barnes",
    "Ross",
    "Henderson",
    "Coleman",
    "Jenkins",
    "Perry",
    "Powell",
    "Long",
    "Patterson",
    "Hughes",
    "Flores",
    "Washington",
    "Butler",
    "Simmons",
    "Foster",
    "Gonzales",
    "Bryant",
    "Alexander",
    "Russell",
    "Griffin",
    "Diaz",
    "Hayes",
  ]

  const firstName = firstNames[Math.floor(Math.random() * firstNames.length)]
  const lastName = lastNames[Math.floor(Math.random() * lastNames.length)]
  const name = `${firstName} ${lastName}`
  const email = `${firstName.toLowerCase()}.${lastName.toLowerCase()}@example.com`
  const role = jobRoles[Math.floor(Math.random() * jobRoles.length)]

  // Get skills for the selected role and randomly select 2-4 skills
  const availableSkills = skillsByRole[role] || []
  const numSkills = Math.floor(Math.random() * 3) + 2 // 2-4 skills
  const shuffledSkills = [...availableSkills].sort(() => 0.5 - Math.random())
  const skills = shuffledSkills.slice(0, Math.min(numSkills, availableSkills.length))

  return {
    id,
    name,
    email,
    role,
    status: statuses[Math.floor(Math.random() * statuses.length)],
    appliedDate: randomDate(),
    experience: Math.floor(Math.random() * 15) + 1,
    location: locations[Math.floor(Math.random() * locations.length)],
    skills,
  }
}

// Generate 100 candidates
export const candidates = Array.from({ length: 100 }, (_, i) => generateCandidate(i + 1))
